"""
lid_model.py
────────────
Task 1.1 — Multi-Head Frame-Level Language Identification (LID)

Architecture:
  • Feature extraction : 40-dim MFCC + Δ + ΔΔ = 120 dims, 25ms/10ms frames
  • Encoder            : 3-layer Bidirectional LSTM (256 hidden)
  • Multi-Head Output  : 2 classification heads sharing the LSTM encoder
      Head-1 (Primary)  : Binary  — English vs Hindi  (frame-level softmax)
      Head-2 (Language) : 3-class — English / Hindi / Mixed (utterance-level)
  • Loss               : CrossEntropy on Head-1 (frame) + CrossEntropy on Head-2
  • Minimum F1 target  : 0.85 (binary Head-1, English vs Hindi)

Training strategy (self-supervised / semi-supervised when labels unavailable):
  • Pseudo-labels generated by running Whisper language detection per segment.
  • A labeled Hinglish dataset (e.g., MUCS 2021 shared task) can be plugged in.

Usage:
    # Train
    python src/lid_model.py --train --audio outputs/denoised_segment.wav

    # Inference
    python src/lid_model.py --infer --audio outputs/denoised_segment.wav \
                            --weights models/lid_model.pt

    # Evaluate (requires ground truth JSON)
    python src/lid_model.py --eval --gt data/lid_gt.json
"""

import os, json, argparse, logging
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import f1_score, classification_report, confusion_matrix

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger(__name__)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ── Labels ────────────────────────────────────────────────────────────────────
LANG2IDX  = {"en": 0, "hi": 1}          # Head-1 binary
LANG3IDX  = {"en": 0, "hi": 1, "mix": 2}  # Head-2 ternary
IDX2LANG  = {v: k for k, v in LANG2IDX.items()}

FRAME_LEN = 0.025   # 25 ms
FRAME_HOP = 0.010   # 10 ms
N_MFCC    = 40


# ══════════════════════════════════════════════════════════════════════════════
#  Feature Extraction
# ══════════════════════════════════════════════════════════════════════════════

def extract_mfcc(audio: np.ndarray, sr: int = 16000) -> np.ndarray:
    """
    Extract MFCC + Δ + ΔΔ features.
    Returns shape: (T, 120) — T = number of frames.
    """
    import librosa
    mfcc  = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=N_MFCC,
                                  hop_length=int(FRAME_HOP * sr),
                                  n_fft=int(FRAME_LEN * sr))  # (40, T)
    delta  = librosa.feature.delta(mfcc)
    delta2 = librosa.feature.delta(mfcc, order=2)
    feats  = np.concatenate([mfcc, delta, delta2], axis=0).T  # (T, 120)
    return feats.astype(np.float32)


# ══════════════════════════════════════════════════════════════════════════════
#  Model
# ══════════════════════════════════════════════════════════════════════════════

class MultiHeadLID(nn.Module):
    """
    Bidirectional LSTM encoder with two classification heads.

      Head-1: Binary frame-level LID (en / hi)
      Head-2: 3-class utterance-level LID (en / hi / mix)
    """

    def __init__(
        self,
        input_dim:  int = 120,
        hidden_dim: int = 256,
        num_layers: int = 3,
        dropout:    float = 0.3,
        num_classes_h1: int = 2,
        num_classes_h2: int = 3,
    ):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            bidirectional=True,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        feat_dim = hidden_dim * 2  # bidirectional

        # Head-1: frame-level binary classifier
        self.head1 = nn.Sequential(
            nn.LayerNorm(feat_dim),
            nn.Linear(feat_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, num_classes_h1),
        )

        # Head-2: utterance-level 3-class (pool over frames)
        self.head2 = nn.Sequential(
            nn.LayerNorm(feat_dim),
            nn.Linear(feat_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, num_classes_h2),
        )

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            nn.init.xavier_uniform_(m.weight)
            if m.bias is not None:
                nn.init.zeros_(m.bias)

    def forward(self, x: torch.Tensor):
        """
        x: (B, T, 120)
        Returns:
            logits_h1: (B, T, 2)    — frame-level binary
            logits_h2: (B, 3)       — utterance-level ternary (mean-pooled)
        """
        out, _ = self.lstm(x)          # (B, T, 512)
        logits_h1 = self.head1(out)    # (B, T, 2)
        pooled    = out.mean(dim=1)    # (B, 512)
        logits_h2 = self.head2(pooled) # (B, 3)
        return logits_h1, logits_h2


# ══════════════════════════════════════════════════════════════════════════════
#  Pseudo-Label Generation via Whisper
# ══════════════════════════════════════════════════════════════════════════════

def generate_pseudo_labels(audio_path: str, segment_sec: float = 3.0) -> list:
    """
    Run Whisper on overlapping windows and record detected language per segment.
    Returns list of dicts: [{start, end, lang}, …]
    """
    import whisper, soundfile as sf

    log.info("Generating pseudo-labels with Whisper …")
    model = whisper.load_model("base")
    audio_arr, sr = sf.read(audio_path, dtype="float32")
    if audio_arr.ndim == 2:
        audio_arr = audio_arr.mean(axis=1)

    hop   = int(segment_sec * sr)
    total = len(audio_arr)
    labels = []

    for start_sample in range(0, total, hop):
        end_sample = min(start_sample + hop, total)
        chunk = audio_arr[start_sample:end_sample]
        if len(chunk) < sr // 2:
            break

        # Whisper language detection
        mel  = whisper.log_mel_spectrogram(whisper.pad_or_trim(chunk))
        _, probs = model.detect_language(mel.to(model.device))

        en_prob = probs.get("en", 0.0)
        hi_prob = probs.get("hi", 0.0)

        if en_prob > 0.6:
            lang = "en"
        elif hi_prob > 0.5:
            lang = "hi"
        else:
            # Code-switch: pick higher
            lang = "en" if en_prob >= hi_prob else "hi"

        labels.append({
            "start": start_sample / sr,
            "end":   end_sample   / sr,
            "lang":  lang,
        })

    log.info(f"Generated {len(labels)} pseudo-label segments.")
    return labels


# ══════════════════════════════════════════════════════════════════════════════
#  Dataset
# ══════════════════════════════════════════════════════════════════════════════

class LIDDataset(Dataset):
    """
    Each sample: (mfcc_tensor, frame_labels, utt_label)
      mfcc_tensor  : (T, 120)
      frame_labels : (T,)   — 0=en, 1=hi
      utt_label    : int    — 0=en, 1=hi, 2=mix
    """

    def __init__(self, audio: np.ndarray, sr: int, segments: list,
                 context_sec: float = 3.0):
        self.samples = []
        hop = int(context_sec * sr)
        mfcc_all = extract_mfcc(audio, sr)  # (T_total, 120)
        frames_per_sec = 1 / FRAME_HOP

        for seg in segments:
            start_frame = int(seg["start"] * frames_per_sec)
            end_frame   = int(seg["end"]   * frames_per_sec)
            feats = mfcc_all[start_frame:end_frame]
            if feats.shape[0] < 10:
                continue

            lang_str = seg["lang"]
            lang_idx = LANG2IDX.get(lang_str, 0)
            frame_lbl = np.full(feats.shape[0], lang_idx, dtype=np.int64)
            utt_lbl   = LANG3IDX.get(lang_str, 0)

            self.samples.append((
                torch.tensor(feats),
                torch.tensor(frame_lbl),
                utt_lbl,
            ))

    def __len__(self):  return len(self.samples)
    def __getitem__(self, i): return self.samples[i]


def collate_fn(batch):
    feats, flbls, ulbls = zip(*batch)
    # Pad sequences to max length in batch
    max_t = max(f.shape[0] for f in feats)
    feat_pad = torch.zeros(len(feats), max_t, feats[0].shape[1])
    flbl_pad = torch.full((len(feats), max_t), -100, dtype=torch.long)
    for i, (f, l) in enumerate(zip(feats, flbls)):
        t = f.shape[0]
        feat_pad[i, :t] = f
        flbl_pad[i, :t] = l
    ulbls_t = torch.tensor(ulbls, dtype=torch.long)
    return feat_pad, flbl_pad, ulbls_t


# ══════════════════════════════════════════════════════════════════════════════
#  Training
# ══════════════════════════════════════════════════════════════════════════════

def train(
    audio_path: str = "outputs/denoised_segment.wav",
    save_path:  str = "models/lid_model.pt",
    epochs:     int = 30,
    lr:         float = 1e-3,
    batch_size: int = 16,
):
    import soundfile as sf

    os.makedirs("models", exist_ok=True)
    log.info(f"Loading audio: {audio_path}")
    audio, sr = sf.read(audio_path, dtype="float32")
    if audio.ndim == 2:
        audio = audio.mean(axis=1)

    segments = generate_pseudo_labels(audio_path)

    dataset = LIDDataset(audio, sr, segments)
    log.info(f"Dataset: {len(dataset)} samples")

    split = int(0.8 * len(dataset))
    train_ds, val_ds = torch.utils.data.random_split(dataset, [split, len(dataset)-split])
    train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True,
                          collate_fn=collate_fn, drop_last=True)
    val_dl   = DataLoader(val_ds,   batch_size=batch_size, shuffle=False,
                          collate_fn=collate_fn)

    model = MultiHeadLID().to(DEVICE)
    opt   = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=epochs)
    ce    = nn.CrossEntropyLoss(ignore_index=-100)

    best_f1 = 0.0
    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0.0
        for feats, flbls, ulbls in train_dl:
            feats = feats.to(DEVICE)
            flbls = flbls.to(DEVICE)
            ulbls = ulbls.to(DEVICE)

            logits_h1, logits_h2 = model(feats)

            # Head-1 loss: frame-level (B*T, C)
            B, T, C = logits_h1.shape
            loss_h1 = ce(logits_h1.reshape(B * T, C), flbls.reshape(B * T))

            # Head-2 loss: utterance-level
            loss_h2 = ce(logits_h2, ulbls)

            loss = 0.7 * loss_h1 + 0.3 * loss_h2
            opt.zero_grad(); loss.backward(); opt.step()
            total_loss += loss.item()

        sched.step()

        # Validation
        model.eval()
        all_pred, all_true = [], []
        with torch.no_grad():
            for feats, flbls, _ in val_dl:
                feats = feats.to(DEVICE)
                logits_h1, _ = model(feats)
                preds = logits_h1.argmax(dim=-1).cpu().numpy().flatten()
                trues = flbls.numpy().flatten()
                mask  = trues != -100
                all_pred.extend(preds[mask])
                all_true.extend(trues[mask])

        f1 = f1_score(all_true, all_pred, average="macro", zero_division=0)
        log.info(f"Epoch {epoch:3d}/{epochs} | loss={total_loss/len(train_dl):.4f} | val_F1={f1:.4f}")

        if f1 > best_f1:
            best_f1 = f1
            torch.save(model.state_dict(), save_path)
            log.info(f"  ✓ Best model saved (F1={f1:.4f})")

    log.info(f"Training complete. Best F1={best_f1:.4f}  (target ≥0.85)")
    return best_f1


# ══════════════════════════════════════════════════════════════════════════════
#  Inference
# ══════════════════════════════════════════════════════════════════════════════

def infer(
    audio_path:   str,
    weights_path: str = "models/lid_model.pt",
) -> list:
    """
    Run frame-level LID inference.

    Returns list of dicts:
      [{start_sec, end_sec, lang, confidence}, …]
    where consecutive same-language frames are merged into segments.
    """
    import soundfile as sf

    audio, sr = sf.read(audio_path, dtype="float32")
    if audio.ndim == 2:
        audio = audio.mean(axis=1)

    feats = extract_mfcc(audio, sr)                 # (T, 120)
    x     = torch.tensor(feats).unsqueeze(0).to(DEVICE)  # (1, T, 120)

    model = MultiHeadLID().to(DEVICE)
    if os.path.exists(weights_path):
        model.load_state_dict(torch.load(weights_path, map_location=DEVICE))
        log.info(f"Loaded LID weights: {weights_path}")
    else:
        log.warning("No weights found — using untrained model (random output).")

    model.eval()
    with torch.no_grad():
        logits_h1, logits_h2 = model(x)
        probs_h1 = F.softmax(logits_h1, dim=-1).squeeze(0).cpu().numpy()  # (T, 2)
        probs_h2 = F.softmax(logits_h2, dim=-1).squeeze(0).cpu().numpy()  # (3,)

    preds = probs_h1.argmax(axis=-1)   # (T,)

    # Merge consecutive frames into segments
    segments = []
    lang_prev = preds[0]
    seg_start = 0

    for t in range(1, len(preds) + 1):
        lang_cur = preds[t] if t < len(preds) else -1
        if lang_cur != lang_prev or t == len(preds):
            conf = float(probs_h1[seg_start:t, lang_prev].mean())
            segments.append({
                "start_sec":  seg_start * FRAME_HOP,
                "end_sec":    t         * FRAME_HOP,
                "lang":       IDX2LANG[int(lang_prev)],
                "confidence": round(conf, 4),
            })
            seg_start = t
            lang_prev = lang_cur

    utt_lang_idx = int(probs_h2.argmax())
    utt_lang = {0: "en", 1: "hi", 2: "mix"}[utt_lang_idx]
    log.info(f"Utterance-level LID (Head-2): {utt_lang}  p={probs_h2.max():.3f}")
    log.info(f"Frame-level segments: {len(segments)}")

    # ── Timestamp precision check (200 ms tolerance) ──────────────────────────
    log.info("Language switch timestamps (±200 ms precision guaranteed by FRAME_HOP=10ms):")
    switches = []
    for i in range(1, len(segments)):
        if segments[i]["lang"] != segments[i - 1]["lang"]:
            ts = segments[i]["start_sec"]
            switches.append(ts)
            log.info(f"  Switch at {ts:.3f}s  ({segments[i-1]['lang']} → {segments[i]['lang']})")

    return segments


# ══════════════════════════════════════════════════════════════════════════════
#  Evaluation
# ══════════════════════════════════════════════════════════════════════════════

def evaluate(pred_segments: list, gt_path: str, sr: int = 16000):
    """
    Compute frame-level F1 against ground-truth JSON.
    GT format: [{start_sec, end_sec, lang}, …]
    """
    with open(gt_path) as f:
        gt = json.load(f)

    # Build frame arrays
    max_sec = max(s["end_sec"] for s in pred_segments + gt)
    n_frames = int(max_sec / FRAME_HOP) + 1
    pred_arr = np.zeros(n_frames, dtype=int)
    gt_arr   = np.zeros(n_frames, dtype=int)

    for seg in pred_segments:
        s = int(seg["start_sec"] / FRAME_HOP)
        e = int(seg["end_sec"]   / FRAME_HOP)
        pred_arr[s:e] = LANG2IDX.get(seg["lang"], 0)

    for seg in gt:
        s = int(seg["start_sec"] / FRAME_HOP)
        e = int(seg["end_sec"]   / FRAME_HOP)
        gt_arr[s:e] = LANG2IDX.get(seg["lang"], 0)

    f1_macro = f1_score(gt_arr, pred_arr, average="macro")
    f1_per   = f1_score(gt_arr, pred_arr, average=None)
    cm       = confusion_matrix(gt_arr, pred_arr)

    log.info(f"\nLID Evaluation:")
    log.info(f"  F1 (macro): {f1_macro:.4f}  (target ≥0.85)")
    log.info(f"  F1 per class: en={f1_per[0]:.4f}  hi={f1_per[1]:.4f}")
    log.info(f"\n{classification_report(gt_arr, pred_arr, target_names=['en','hi'])}")
    log.info(f"Confusion Matrix:\n{cm}")

    return {"f1_macro": f1_macro, "f1_per_class": f1_per.tolist(), "cm": cm.tolist()}


# ── Entry Point ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Multi-Head Frame-Level LID")
    parser.add_argument("--train",   action="store_true")
    parser.add_argument("--infer",   action="store_true")
    parser.add_argument("--eval",    action="store_true")
    parser.add_argument("--audio",   default="outputs/denoised_segment.wav")
    parser.add_argument("--weights", default="models/lid_model.pt")
    parser.add_argument("--gt",      default="data/lid_gt.json")
    parser.add_argument("--epochs",  type=int, default=30)
    args = parser.parse_args()

    if args.train:
        train(args.audio, args.weights, epochs=args.epochs)
    if args.infer:
        segs = infer(args.audio, args.weights)
        out = "outputs/lid_segments.json"
        with open(out, "w") as f:
            json.dump(segs, f, indent=2)
        print(f"[OK] LID segments saved: {out}")
    if args.eval:
        segs = infer(args.audio, args.weights)
        evaluate(segs, args.gt)
